# Generated by Django 5.2.5 on 2025-08-27 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_blog_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes_new',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
